[workspace]
resolver= "3"
members = [ "LeetCode/easy",
    "abc300",
    "abc301", "abc302",
    "abc400",
  "abc401", "abc402", "abc403", "abc418", "abc419", "abc422", "practice",
]

[workspace.dependencies]
proconio = { version = "0.4", features = ["derive"]}
